workspace/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'main/about'

  get 'main/contact'

  get 'main/index'

  get 'main/about'

  get 'main/contact'
  
  root 'main#index'

end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/main_helper.rb
module MainHelper
end

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Crete+Round' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class = "nav dropdown">
    <button id = "dLabel" type = "button" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">
      >
      Dropdown trigger
      <span class = "caret"></span>
      
      </button>
      
      <ul class ="dropdown-menu" aria-labelledby="dLabel">
        <li><%= link_to('Contact', main_contact_path) %> </li>
        <li><%= link_to('Home', root_path) %> </li> 
        <li> <%=link_to('About', main_about_path) %> </li>
        
        
      </ul>
      </div>

<%= yield %>

  <div class="contact">
    Contact Form
  </div>
  <div class="footer"></div>
  Footer links 
</body>
</html>
 

workspace/app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

workspace/app/views/main/contact.html.erb
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

workspace/app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

<div class="hero">
        <h1> Jared is a very good teacher</h1>
            
</div>




<div class="copy">
    <div class = "container">
        <div class = "col-sm-4"></div>
            <img src = "http://wallpaperspoints.com/wp-content/uploads/2013/09/siamese-cat-high-quality-wallpapers.jpg"> 
    <p> <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, debitis, accusantium, rerum, quisquam provident id vel voluptatibus minima repellat architecto doloremque tenetur facere temporibus delectus possimus repudiandae quis aliquid ad.</div>
    <div>Distinctio, impedit, deserunt, qui, explicabo nemo tempora soluta veniam asperiores minima earum illo ea nostrum ex dignissimos voluptates possimus nihil vitae accusamus dolor cupiditate. Alias, quasi blanditiis dolores necessitatibus nisi.</div>
    <div>Similique in odio aperiam saepe alias est magnam deleniti optio possimus labore! Neque, quia, magnam, accusamus, a nam facilis magni adipisci dolores ipsum dolore sequi at molestias tenetur saepe eaque!</div>
    <div>Ut, facilis, eum magni eligendi dolorem quasi beatae rerum itaque delectus deserunt culpa debitis modi laborum tempora vitae commodi eius laboriosam error nobis praesentium maiores cum blanditiis vero neque expedita.</div>
    <div>Dolores, illum, est eveniet aliquam voluptate harum vitae cupiditate inventore consectetur eaque quas asperiores ea sapiente sunt aut aspernatur distinctio veniam voluptatum. Iure, error ab ducimus expedita consectetur maxime dolorem?</div> </p>
    </div>
</div>

<div class="content">
    <div class = "long-content">
   <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, voluptate cupiditate repellat nemo animi quibusdam quo quisquam quia aut corporis rem reiciendis modi laboriosam perspiciatis aspernatur sunt placeat provident ipsa.</div>
   epellendus, necessitatibus adipisci dolore magnam nobis eveniet expedita. Sit, quisquam commodi sed dicta quae beatae. Minima, nisi inventore quod reiciendis similique animi esse beatae nemo repellendus quisquam. Unde, eaque, cumque.</div>
   Dicta, odio minima provident debitis vero rerum harum reiciendis recusandae atque similique sequi soluta odit explicabo laudantium sunt quis perferendis sint eveniet eum nostrum. Officia iste molestias quibusdam ratione quis.</div>
   ugit, autem, ratione animi obcaecati repudiandae minima possimus vero hic aperiam provident quod debitis harum quae tenetur modi odio cumque ipsam ex eligendi cum nisi nostrum in facere deleniti illum!</div>
   Corporis, reiciendis, nobis, accusantium necessitatibus iure dolorem deserunt modi aut obcaecati excepturi magnam tempore quod unde beatae deleniti voluptate quibusdam dolore itaque odio laboriosam cumque possimus sint et facere illum.</div>
    </p>
    
    
    <span>             
    
    </span>
    
</div>
    
    </p>
    </p>
    </p>
    <div class = "container"> 
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, voluptate cupiditate repellat nemo animi quibusdam quo quisquam quia aut corporis rem reiciendis modi laboriosam perspiciatis aspernatur sunt placeat provident ipsa.</div>
    <div>Repellendus, necessitatibus adipisci dolore magnam nobis eveniet expedita. Sit, quisquam commodi sed dicta quae beatae. Minima, nisi inventore quod reiciendis similique animi esse beatae nemo repellendus quisquam. Unde, eaque, cumque.</div>
    <div>Dicta, odio minima provident debitis vero rerum harum reiciendis recusandae atque similique sequi soluta odit explicabo laudantium sunt quis perferendis sint eveniet eum nostrum. Officia iste molestias quibusdam ratione quis.</div>
    <div>Fugit, autem, ratione animi obcaecati repudiandae minima possimus vero hic aperiam provident quod debitis harum quae tenetur modi odio cumque ipsam ex eligendi cum nisi nostrum in facere deleniti illum!</div>
    <div>Corporis, reiciendis, nobis, accusantium necessitatibus iure dolorem deserunt modi aut obcaecati excepturi magnam tempore quod unde beatae deleniti voluptate quibusdam dolore itaque odio laboriosam cumque possimus sint et facere illum.</div>
</div>
</div>